version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_tka_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password_rahasia_anda
      MYSQL_DATABASE: db_psikometri
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: streamlit_tka_app
    restart: always
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password_rahasia_anda
      - DB_NAME=db_psikometri
    depends_on:
      - db

volumes:
  mysql_data: